### ISSUE TITLE
Just wondering 

### ISSUE THREAD

**Issue by DomainAdministrator** [MillionDollarScript/MillionDollarScript#35]
is everything up to date in regards to the script heading into 2016? I am wanting to try it to for a few projects so just checking to make sure everything up to date?

**Comment by ty2u** [comment]
Hi there,

I wouldn't really consider it up to date as far as 3rd party libs are concerned. I would consider it always a work in progress. It might work for you but I haven't had time to work on it a lot lately or fix everything I want to yet. The work I've done is all on the dev branch.

Since I took over development a number of years ago I've fixed a lot of bugs and tried to make it more secure, though I can't be certain it is super secure since I've never tested it's security. I do think it probably wasn't very secure originally before it was given to me. I do try to fix most things people report when I have time.

I've decided to sort of stop spending time on that version and have been converting it, or rather rewriting it from scratch as a WordPress plugin. I want to attempt to import grids and orders and users and whatnot from installs of older versions but I'm not sure how well that will work since a lot of options will likely be different. But I do want to make it a lot more resource friendly so that pretty much any size or maybe even any shape of grid could be created. The only restriction might be the visitors browser running out of memory or something, not really sure just yet.

Good luck!

**Comment by DomainAdministrator** [comment]
Thanks for the update. i'm very interested in the wp plugin progress so please keep me in the loop.

**Comment by ty2u** [comment]
I have actually been working on the plugin now and then, including several hours in the past couple days. But it still has a ways to go before anything is ready to test. It seems to be turning out fairly solid so far though so maybe I can just work on it some more and see how it goes.
