### ISSUE TITLE
Not able to install properly

### ISSUE THREAD

**Issue by prabupragmatic** [MillionDollarScript/MillionDollarScript#45]
Hi

I'm facing following error when installing. Not able to install properly. Please see attached screen for home page after install. Please help.
Error: Invalid default value for 'ad_date'(
Error: Invalid default value for 'publish_date'(
Error: Table 'pragmat2_mdsdb.banners' doesn't exist(
Error: Invalid default value for 'order_date'(
Error: Invalid default value for 'date'(
Error: Invalid default value for 'SignupDate'(
Error: Invalid default value for 'mail_date'(

![mds](https://cloud.githubusercontent.com/assets/23399228/20212560/ded711e2-a829-11e6-98c3-8ee7eb556317.png)

**Comment by ty2u** [comment]
Hi there,

Thank you for the report!

This is possibly due to the MySQL version. I remember having a similar error with MySQL before somewhere and I believe it was because newer versions of MySQL don't like the date field being all zeroes and the year has to be at least 1000. So I will fix that up when I get a chance in the next couple days.

Ryan

**Comment by ty2u** [comment]
It appears that the changes I made are to accommodate newer versions of MySQL but perhaps that affects older versions. Which version of MySQL are you using?

Here are the changes made which might be the issue, if you want to change them back to see if you can make it work:
https://github.com/MillionDollarScript/MillionDollarScript/commit/007547914cbea5f1d172cb8928d2ab6cb18d5216

I think the ideal solution might be to have the code check the MySQL version and use a different install file based on which version it finds. However I don't know if I will do this or not since I am looking forward to the next version of MDS which will be a WordPress plugin. If I get time though I certainly will look into it further and post here.

**Comment by prabupragmatic** [comment]
Hi

Thanks for reply. Now i'm able to install script on my server using changes you suggested. But cant'access admin. There is no effect when input the password. Where do i see or add admin password?

We want to develop website like as a http://www.milliondollarhomepage.com/. 

So i expect your comments for following queries

1)Is this script is a stable one to develop website like http://www.milliondollarhomepage.com/?(With out script related issues)

2) Do you've a time line to complete WordPress plugin (MDS version)?(Because we feel its better to start with WordPress instead of this script)

3) Or if we use this current script how much you expect to provide technical support for one month?

Please let us know your comments. We're waiting for your response to move forward.

**Comment by ty2u** [comment]
Hi there,

The default password is: ok

It's not the best password but I didn't make it that so you definitely can change it in the Main Config. There is an Admin Password option in there once you login.

I wouldn't say the script is stable yet since I haven't tested it live anywhere yet which is why it's in a dev state. People have seemed to be using it successfully at some points and when they reported bugs I attempted to fix them. I'm not sure if it always worked or not. If you want to try it out and see if it works for you then you're more than welcome to and if you find any bugs or other issues feel free to post them and I'll definitely work on them when I can.

You can make a site like that, I'm pretty sure. I haven't actually looked at it for awhile but it did seem pretty similar the last time I did. You can also use WordPress. In it's current state you can still use WordPress and just link to or paste the HTML code given for the iframes in the MDS admin area. However I'm not sure that will necessarily work in WordPress without either hard coding it into a page template or widget or shortcode or something or using a plugin of some sort maybe.

**Comment by prabupragmatic** [comment]
Hi

Great. When you've planned to release WordPress plugin (MDS version)?

Thanks.

**Comment by ty2u** [comment]
I don't have any set date yet, it still requires a lot of work, although I have started on it nothing is ready yet.

**Comment by prabupragmatic** [comment]
Hi

Now i'm using your script. I've added 32*32 (w*h) image with ad link. System takes 1600 pixels for this 32*32 (w*h) image. Can you please explain how system was calculated 1600 pixels?

And as a user i required to purchase 1000 pixels before upload the ad image. Now system calculate pixel count after image upload. How is this possible with your script?

Please advice. Thanks in advance.

**Comment by ty2u** [comment]
Hi there,

Sorry I'm not sure I completely understand what you're asking. Though it could be because I just woke up and haven't had my tea yet.

Are you saying you uploaded an image that was 32 x 32 pixels and it takes up 1600 pixels? Have you changed any of your grid settings such as the block size or anything else?

**Comment by prabupragmatic** [comment]
Hi

Great. Just now i saw the grid management option at the admin section. No issues. I will manage.

One clarification. If a user wants to buy 30 pixel how do we do that?

**Comment by ty2u** [comment]
You must first setup a payment module and configure it. Then I believe they should just be able to order pixels like normal by uploading their image and selecting it's location and paying for it.

**Comment by prabupragmatic** [comment]
Hi

Thanks. I would like to change settings like user needs to purchase pixel first and they can upload their image after successful payment in allocated space. Is this possible?

**Comment by ty2u** [comment]
The way it works is that you select your pixels first and then pay. I'm not sure how much work it would require to change it around but I suspect a fair amount. I know you can use other pixel selection methods to require the user to create an account first before being able to select their pixels but I'm also not sure how reliable those methods are.

**Comment by prabupragmatic** [comment]
Hi

Thanks for reply. Sorry to disturb you :)

I'm facing one more issue. I've tried to upload 8*8(w*h)) size image as a
user. After upload i cant track and place that image in grid.

Note : As you know its required 100 pixels or one block.

Please help.

If you don't mind can you please try to upload this attached image as a
user in my site using test login details below

to see the issue.

http://pragmaticsolutioninc.com/client_works/mdh/users/

User login details

member id :18

password : littlemaster
