### ISSUE TITLE
Why There is no image that display in the pixel block eventhough there are already 6 image that being completed

### ISSUE THREAD

**Issue by AzhrafAlias** [MillionDollarScript/MillionDollarScript#54]
Why There is no image that display in the pixel block eventhough there are already 6 image that being completed..

But when i move my mouse cursor to the block, the image will be display like the  screenshot below

Please help,

Thanks

![image](https://cloud.githubusercontent.com/assets/12478493/24736149/f5bb2748-1ab8-11e7-9e0d-e6fd3b5e99f3.png)

**Comment by ty2u** [comment]
Hi there,

You could try running the Process Pixels task from the admin and see if that helps.

If not maybe your host isn't giving your site enough RAM for PHP. Try to adjust the setting to 64MB in the Main Config. If that doesn't work maybe you are getting some errors in your error log you could send me. You may have to adjust the error reporting option to say E_ALL instead of 0 and try to Process Pixels again to see if it gives an error.

**Comment by AzhrafAlias** [comment]
Solve it by do the Process Pixels task...thanks ya

**Comment by ty2u** [comment]
Great! I believe it normally should automatically run this task when an order successfully completes.
