### ISSUE TITLE
1x1 pixel sell

### ISSUE THREAD

**Issue by bear70** [MillionDollarScript/MillionDollarScript#62]
how to manage to sell 1 pixel, in admin area minimum is 10x10=100 pixels equal 100 usd, thanks for answer in advance.

**Comment by ty2u** [comment]
You would have to edit your grid in the admin under Manage Grids and adjust your block size to 1x1 and then resize the images to be all 1x1 pixel and upload those instead of the 10x10 ones that are there. However this would make it pretty hard for people to see a 1 pixel image. So therefore you should set a min blocks higher in there as well.

**Comment by bear70** [comment]
helo, so in curent version of script i can not buy 1 pixel, its adjusted 10x10 minimum

**Comment by bear70** [comment]
![screenhunter_87 jul 18 19 43](https://user-images.githubusercontent.com/30246970/28331465-79f72d16-6bf1-11e7-872e-8e6ae3ddc7a4.jpg)

**Comment by bear70** [comment]
can somebody want to view if i was made error in admin area? Thanks for answer in advance.

**Comment by ty2u** [comment]
You can certainly set the block size to 1 x 1. In the image you have them set to 4 x 4. You also have your Grid Width and Grid Height set to 1 block and therefore in your case your grid will also only be 4 x 4.

The Grid Width and Grid Height should be set to your total grid dimensions in pixels divided by the block size. For example if your block size was 1 x 1 and you wanted your grid to be 1000 x 1000 you would set your Grid Width and Grid Height to 1000 x 1000. If your block size was 10 and you wanted your grid to be 1000 x 1000 you would set your Grid Width and Grid Height to 100 x 100. If your block size is 4 x 4 then you would want to set them to 250 x 250 for a 1000 x 1000 sized grid.

Also note that you cannot/should not change the Grid Width and Grid Height after orders are made on it because it won't scale properly. You can change them but if you click the Edit anyway link but the images won't scale properly due to the existing orders.

**Comment by bear70** [comment]
![screenhunter_87 jul 19 16 00](https://user-images.githubusercontent.com/30246970/28371884-79d70d12-6c9e-11e7-84a9-c42db62a3c66.jpg)
can somebody tell me what to do? I was installed new script by default, but when i want to buy 1 pixel script gives me block of 100 usd.

**Comment by ty2u** [comment]
The price per block is set to 100. A block is 10x10 pixels by default.

-------- Original message --------
