### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by JGCdesign** [MillionDollarScript/MillionDollarScript#66]
Hello, I have Spanish translation for this script. Do you want it to upload to repository?
Regards!

**Comment by ty2u** [comment]
Sorry for the delayed response. Thank you for the offer. However, that is unnecessary because I'm rewriting this as a WordPress plugin. However, once that is ready any translations are welcome but I may use some other type of tool/service to create them. They will use po/mo files since that's how it works in WP.

**Comment by JGCdesign** [comment]
Hello Ryan,
If you are interested in translate this PO/MO files to Spanish, i do it for
you. You can advice me when the plugin is developed, i do this work for
you.
Thanks for your attention.
Regards!

2017-11-20 17:36 GMT+01:00 Ryan <notifications@github.com>:

**Comment by ty2u** [comment]
Awesome, thanks! It will probably go through translate.wordpress.org when it's done. It seems to be taking quite awhile though as I keep running into major issues I can't seem to get around very easily without changing the entire design or waiting for them to fix bugs, usually in WooCommerce. But hopefully it's moving along nicely again now. Woohoo!
