### ISSUE TITLE
Problem with expiring orders

### ISSUE THREAD

**Issue by Phobos7** [MillionDollarScript/MillionDollarScript#67]
Dear Ryan,

Thank you for this amazing software! I really appreciate the hard work and effort you have put into it.

However, there is a feature that is not working for me.
If I set the pixels to expire in 1 day, the orders do not expire, and I can't figure out why.
When clicking on Orders: Expired link from the Admin menu, no order is shown as expired and therefore they are NOT deleted from the Grid after clicking on "Process Pixels" as they should be.
Yet, if I click on Map of Orders, and hover over the order, there is an "Expired!" message in the end of the "Expires:" tag. Example: "Expires: 1d 5h 52m passed -52m to go (1)Expired!"

I wonder why this happens??
I have tested it in at least 3 virtual machines (Ubuntu 14 or 16 + XAMPP) and I get the same problem.
I have granted permissions 777 in every directory, subdirectory and file.
I am using the MDS ver. 2.1-dev from your website (not from Github, there are some differences I understand).

Can you please help me?

**Comment by ty2u** [comment]
Hi there,

That sounds like probably a bug in the code somewhere. I will fix it up today or tomorrow at some point and push a fix to github.

These days the latest version on the github dev branch and the download from the website are the same. The master branch on github is what the original script was before I took over development and the dev branch contains all the changes I've made to it since then. So you should be able to download from the website to get the update once I push a fix if that's easier.

It's unlikely you would have to have all directories and files be 777 and I know you're just testing but you certainly wouldn't want to do that in a production environment. This is also likely not the cause of the issue. Depending on how your server is setup you might only have to chmod a few things to allow it to access them, or you might not have to change anything. I'm not sure how XAMPP does it but I know that if you happen to use Virtualmin to setup your web server it will set it up quite nicely so that you shouldn't have to change anything.

If you ever have any other issues feel free to ask for some help and keep bugging me if I don't respond, sometimes I get busy and don't notice =)

**Comment by Phobos7** [comment]
Thank you so much for the ultra-fast reply!

Great! I 'll be checking for new updates. :)
If you happen to solve this issue, drop me a line and I will download and test the new version ASAP.

I have a paranoid (lol) suggestion to make (if it is easy and does not break anything).
In order to replicate and test the expiry feature fast, can you allow floats in the Days to expire?
For example expire in 0.0007 days to expire the order after ~ 1 min?

You are correct, I was comparing the # of files between the Github version and the one I had initially downloaded in my pc from your website a month earlier. That version was from 15 of August, yet you updated the script, this is why I got confused. Don't worry though, I am 99.99% sure that the problem exists in the latest version, because I re-downloaded it (multiple times) from your website inside the VMs rather than copying the "old" version that I had for reference.

I know I shouldn't give 777 everywhere, but as you mentioned, I was testing. I thought that it might be a permission error. You see, after copying the script to htdocs (XAMPPs /www dir), I did the following:

sudo chmod 777 /opt/lampp/htdocs/admin/temp
sudo chmod 777 /opt/lampp/htdocs/pixels
sudo chmod 666 /opt/lampp/htdocs/config.php
sudo chmod 666 /opt/lampp/htdocs/lang/english.php
sudo chmod 777 /opt/lampp/htdocs/upload_files/docs
sudo chmod 777 /opt/lampp/htdocs/upload_files/images
sudo chmod 777 /opt/lampp/htdocs/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

However, with those permissions, it is possible to generate a .png grid, while it is impossible to generate a .gif grid!!

I was racking my brains for 3 hours why this simple thing wouldn't work and finally after enabling error_reporting (uncommenting 1st line in config.php) I was able to realize it was a permissions error. 

To avoid any other frustrating permission error at the testing stage, I did

sudo chmod 777 -R /opt/lampp/htdocs

which solved all problems, except order expiration of course.

I would like an advise as to what would be the best (strictest but 100% working) permissions be.
I am thinking doing:

sudo find /opt/lampp/htdocs -type d -exec chmod 755 {} +
sudo find /opt/lampp/htdocs -type f -exec chmod 644 {} +

sudo chmod 777 /opt/lampp/htdocs/admin/temp
sudo chmod 777 /opt/lampp/htdocs/pixels
sudo chmod 777 /opt/lampp/htdocs/upload_files/docs
sudo chmod 777 /opt/lampp/htdocs/upload_files/images
sudo chmod 777 /opt/lampp/htdocs/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

sudo chmod 666 /opt/lampp/htdocs/config.php
sudo chmod 666 /opt/lampp/htdocs/lang/english.php

are these secure enough?

If yes I will use them and test for 100% functionality for the next version.

Best wishes!
Hope you crush that bug soon! =)

**Comment by ty2u** [comment]
Yeah that should be ok. You could also try running through php-fcgi or suexec or something to run as the same user as your web server.

I've fixed the bug but haven't pushed it yet. Will do that soon.

If you want to adjust the file manually you can.

Edit /includes/functions.php around line 84 and change this:
```
if (isset($_REQUEST['time']) && $_REQUEST['time']=='') {
	if (defined(NO_HOUSE_KEEP) && NO_HOUSE_KEEP!='YES') {
		expire_orders();
	}
}
```

To this:
```
if (!defined(NO_HOUSE_KEEP) || NO_HOUSE_KEEP != 'YES') {
	expire_orders();
}
```

I may adjust it a bit differently than that before pushing it to github.

Also if you wanted you could just remove that code or leave it since it doesn't do anything anyway and make a separate cron.php file in the root of the install and add this to it instead and run it on a cronjob each minute or however often you want to check for expired pixels:

```
<?php
define("MDSROOT", dirname(__FILE__));
include_once (MDSROOT . "/config.php");
expire_orders();
```

Hopefully that would work. I haven't tested it.

**Comment by Phobos7** [comment]
Congratulations!

Solution #1 worked in 2 environments.
Is solution #2 better than #1?
If yes, I am not sure how to run a cron php job, I guess I will google it.

Anyway, I would like to mention 2 things:

1) I run into an interesting situation: The expired blocks are now marked as ordered, although they have expired more than 1 day ago (How many days to keep Expired orders before cancellation? = 1). However I believe that the countdown starts from the time that the order was flagged as expired, not when it actually expired and thus this is not a bug. It makes perfect sense. :)

2) With the permissions I mentioned, there is still a problem with the .gif format or png with multiple grids. Everything else seems to be in order.

After some painful testing:

Fatal error: Uncaught ErrorException: imagegif(/opt/lampp/htdocs/pixels/bg-main1.gif): failed to open stream: Permission denied in /opt/lampp/htdocs/vendor/imagine/imagine/lib/Imagine/Gd/Image.php:580 Stack trace: #0 [internal function]: Imagine\Gd\Image->Imagine\Gd\{closure}(2, 'imagegif(/opt/l...', '/opt/lampp/htdo...', 580, Array) #1 [internal function]: imagegif(Resource id #84, '/opt/lampp/htdo...') #2 /opt/lampp/htdocs/vendor/imagine/imagine/lib/Imagine/Gd/Image.php(580): call_user_func_array('imagegif', Array) #3 /opt/lampp/htdocs/vendor/imagine/imagine/lib/Imagine/Gd/Image.php(233): Imagine\Gd\Image->saveOrOutput('gif', Array, '/opt/lampp/htdo...') #4 /opt/lampp/htdocs/include/image_functions.php(70): Imagine\Gd\Image->save('/opt/lampp/htdo...') #5 /opt/lampp/htdocs/admin/process.php(50): publish_image('1') #6 {main} Next Imagine\Exception\RuntimeException: imagegif(/opt/lampp/htdocs/pixels/bg-main1.gif): failed to open stream: Permission denied in /opt/lampp/htdocs/vendor/imagine/imagine/lib/Imagine/Gd/Image.php in /opt/lampp/htdocs/vendor/imagine/imagine/lib/Imagine/Gd/Image.php on line 697

Should I relax some permission? Which one?

Thanks a lot!

**Comment by Phobos7** [comment]
I think I have found the problem. There are already 2 main.gifs in the /admin/temp folder.
If I delete those manually and retry to generate them with process pixels, everything goes fine.

Thanks again so much for your valuable help! 👍 

Hope I didn't bug you too much :)
